#MODEL:
#  TYPE: swin
#  NAME: swin_tiny_patch4_window7_224
#  DROP_PATH_RATE: 0.2
#  PRETRAIN_CKPT: "./pretrained_ckpt/swin_tiny_patch4_window7_224.pth"
#  SWIN:
#    FINAL_UPSAMPLE: "expand_first"
#    EMBED_DIM: 96
#    DEPTHS: [ 2, 2, 2, 2 ]
#    DECODER_DEPTHS: [ 2, 2, 2, 1]
#    NUM_HEADS: [ 3, 6, 12, 24 ]
#    WINDOW_SIZE: 7

MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: "./pretrained_ckpt/swin_tiny_patch4_window7_224.pth"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 2]
    NUM_HEADS: [ 3, 6, 12]
    WINDOW_SIZE: 7



#DATA:
#  IMG_SIZE: 384
#MODEL:
#  TYPE: swin
#  NAME: swin_base_patch4_window12_384
#  PRETRAIN_CKPT: "./pretrained_ckpt/swin_base_patch4_window12_384.pth"
#  SWIN:
#    EMBED_DIM: 128
#    DEPTHS: [ 2, 2, 2 ]
#    NUM_HEADS: [ 4, 8, 16]
#    WINDOW_SIZE: 12
#TEST:
#  CROP: False